services:
  jenkins:
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    container_name: parabank-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - selenium-chrome
    networks:
      - parabank-network

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: parabank-selenium
    restart: unless-stopped
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - parabank-network

volumes:
  jenkins_home:

networks:
  parabank-network:
    driver: bridge