[pytest]
pythonpath = .



addopts =
    -v
    --tb=short
    --strict-markers



markers =
    api: API tests
    ui: UI tests
    smoke: Smoke tests
    regression: Regression tests
    positive: Positive tests
    negative: Negative tests
    external: Tests using external web resources

